steps:
  - id: "build-docker-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_VERSION}"
      - "-f"
      - "build/package/Dockerfile"
      - "."
    dir: "."

  - id: "push-docker-image-to-gcr"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_VERSION}"
    dir: "."

tags: ["$_PROJECT_ID", "$_IMAGE_NAME", "$_IMAGE_VERSION", "docker", "deploy"]

# Change _PROJECT_ID in deploy.yaml
substitutions:
  _PROJECT_ID: "ingka-so-cripftools-cicd"
  _IMAGE_NAME: "buyable-report"
  _IMAGE_VERSION: "1.2.36"

